//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Login
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string designation { get; set; }
        public string email { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<int> isAdmin { get; set; }
        public string picpath { get; set; }
    }
}
